name: Deploy Terraform

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform:
    name: Deploy Terraform Job
    runs-on: ubuntu-latest

    steps:
      # Pulls the latest version of your code from the GitHub repository
      - name: Checkout code
        uses: actions/checkout@v2

      # Installs Terraform on the GitHub runner
      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      # Configures your AWS access by using the credentials stored in GitHub Secrets
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: "eu-east-1"
      
      - name: Verify AWS CLI
        run: aws sts get-caller-identity

      # Run TFLint using official action
      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v1

      - name: Run TFLint
        run: tflint

      # Run tfsec using official action
      - name: Run tfsec Scan
        uses: aquasecurity/tfsec-action@v1.0.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}

      # Initialize terraform
      - name: Initialize Terraform
        run: terraform init

      - name: Terraform Format Check
        run: terraform fmt -check

      - name: Terraform Validate
        run: terraform validate

      # This step runs terraform plan on pull requests
      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        run: terraform plan

      # These steps run on push to main branch (merge)
      - name: Terraform Apply
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve
      
      # Uncomment this to destroy terraform resources on push to main branch (use with caution!)
      # - name: Terraform Destroy
      #   if: github.event_name == 'push' && github.ref == 'refs/heads/main'
      #   run: terraform destroy -auto-approve

      # Execute the terraform plan
      #- name: Terraform Plan
      #  run: terraform plan

      # Deploy terraform changes
      #- name: Terraform Apply
      #  run: terraform apply -auto-approve

      # Destroy terraform resources (uncomment lines below)
      # - name: Terraform Destroy
      #   run: terraform destroy -auto-approve